classDiagram
    Editable <|--Product
    Product <|--Ticket
    Product <|--Publication
    Publication <|-- Book
    Publication <|-- Magazine
    Magazine <|-- DiscMag
    SaleableItem <|.. Product
    Serializable <|.. Product
    Product <-- CashTill
    Product <|-- Stationary
    Stationary <|-- Pen
    Stationary <|-- Notebook
    Product <|-- MusicCollection
    MusicCollection <|-- Album
    MusicCollection <|-- Single
    Album "1" *-- "1..*" Music
    Single "1" *-- "1" Music


    class Product{
        -String productId
    }

    class Serializable{
        <<interface>>
    }
    class Ticket{
        -String description
        -double price
        +sellItem()
    }
    class Editable{
        <<abstract>>
        -Scanner input
        +String getInput(String)
        +int getInput(int)
        +double getInput(double)
        +boolean getInput(boolean)
        +Date getInput(Date)
        +Enum getInput(Enum)
        +edit()*
        +initialize()*

    }
    class Publication{
        <<Abstract>>
        -String title
        -double price
        -int copies
        +getPrice()

        +Publication()
        +Publication(String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Book{
        -String author
        +edit()
        +initialize()
        +sellItem()

        +Book()
        +Book(String author)
        +Book(String author, String title, double price, int copies)
        +toString()
        +equals()
        +hashCode()

    }
    class Magazine{
        -int orderQty
        -java.util.Date currentIssue

        +Magazine()
        +Magazine(int orderQty, Date currentIssue, \n String title, double price, int copies)

        +edit()
        +initialize()
        +sellItem()
    }
    class DiscMag{
        -boolean hasDisc
        +edit()
        +initialize()
        +sellItem()

        +DiscMag()
        +DiscMag(boolean, hasDisc, int orderQty, Date currentIssue, \n String title, double price, int copies)

    }
    class CashTill{
        -double runningTotal
        +CashTill()
        +showTotal()
        +sellItem(SaleableItem item)
    }
    class SaleableItem {
        <<interface>>
        +sellItem()
        +getPrice()
    }

    %% Directed Task

    class Stationary {
        <<Abstract>>
        -String brand
        -double price
        -int quantity

        +getPrice()
        +toString()
        +equals()
        +hashCode()
    }

    class Pen {
        -String color

        +Pen()
        +Pen(String color)
        +edit()
        +initialize()
        +toString()
        +sellItem()
    }

    class Notebook {
        -int pageCount

        +Notebook()
        +Notebook(int pageCount)
        +edit()
        +initialize()
        +toString()
        +sellItem()
    }

    %% Initiative Task
    %% My idea: sell music in digital format

    %% I decided to set cover as a string so it can store an image link
    class MusicCollection{
        <<Abstract>>>
        -String title
        -String artist
        -String genre
        -double price

        +getPrice()
        +toString()
        +equals()
        +hashCode()
    }

    class Album {
        -int musicQuantity

        +Album()
        +Album(String title, String artist, String genre, double price, \n int musicQuantity, Array<Music> musics)
        +edit()
        +initialize()
        +toString()
        +sellItem()
    }

    class Single {
        +Single()
        +Single(String title, String artist, String genre, double price, \n int musicQuantity, Music music)
        +edit()
        +initialize()
        +toString()
        +sellItem()
    }

    class Music {
        -String title
        -Time duration
    }



